services:
  - type: web
    name: smart-accident-detector
    env: python
    buildCommand: pip install -r requirements.txt
    # FIX: Added --timeout and --preload to prevent worker timeouts during slow model loading
    startCommand: gunicorn app:app --workers 1 --bind 0.0.0.0:$PORT --timeout 300 --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: WEB_CONCURRENCY
        value: 1